version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5002:5002"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=sentiment_press_db_dev
      - POSTGRES_USER=rumble
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  frontend:
    build: ./sentiment-press-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=sentiment_press_db_dev
      - POSTGRES_USER=rumble
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
