name: CI for Flask Backend

on:
  push:
    branches:
      - dev  # Trigger CI on pushes to dev branch (you can add other branches like main if you prefer)
  pull_request:
    branches:
      - dev  # Trigger CI on pull requests targeting dev branch

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this if you want to use a different OS
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Match the Python version for your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Path to your backend requirements

      - name: Run Pytest
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost/test_db  # Make sure your tests use this env variable
        run: |
          pytest backend/tests  # Path to your tests directory
