name: CI for Flask Backend

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: sentiment_press_db_test  # Database name
      POSTGRES_USER: postgres  # DB user
      POSTGRES_PASSWORD: password  # DB password
      APP_ENV: test  # Set app to test mode to use the test database

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migrations
        run: |
          source venv/bin/activate
          flask db upgrade

      - name: Run tests
        run: python -m pytest
