name: CI for Flask Backend

on:
  push:
    branches:
      - dev  # Trigger CI on pushes to dev branch (you can add other branches like main if you prefer)
  pull_request:
    branches:
      - dev  # Trigger CI on pull requests targeting dev branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost/test_db
